# Use the official Python image from the Docker Hub
FROM python:3.12.7-slim



# Set the working directory in the container
WORKDIR /src

# Copy the requirements file to the working directory
COPY requirements.txt /src/

# Update pip and install the requirements
RUN pip install --upgrade pip && pip install -r requirements.txt

# Remove the requirements file
RUN rm requirements.txt

# Copy the entire bot folder to the working directory
COPY bot/ /src/
COPY main.py /src/

EXPOSE 443

# Set the entrypoint to run the Python script
ENTRYPOINT ["python", "main.py"]